### ISSUE TITLE
Not all ways happen,something ,these exception will throw

### ISSUE THREAD

**Issue by k-lam** [TonicArtos/StickyGridHeaders#114]
java.lang.NullPointerException
    at com.tonicartos.widget.stickygridheaders.StickyGridHeadersBaseAdapterWrapper.getView(StickyGridHeadersBaseAdapterWrapper.java:193)
    at android.widget.AbsListView.obtainView(AbsListView.java:2305)
    at android.widget.GridView.makeAndAddView(GridView.java:1345)
    at android.widget.GridView.makeRow(GridView.java:345)
    at android.widget.GridView.fillDown(GridView.java:287)
    at android.widget.GridView.fillFromTop(GridView.java:421)
    at android.widget.GridView.layoutChildren(GridView.java:1233)
    at android.widget.AbsListView.onTouchMove(AbsListView.java:3629)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:3499)
    at com.tonicartos.widget.stickygridheaders.StickyGridHeadersGridView.onTouchEvent(StickyGridHeadersGridView.java:344)
    at android.view.View.dispatchTouchEvent(View.java:7723)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2117)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1564)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2493)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2065)
    at android.view.View.dispatchPointerEvent(View.java:7903)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4188)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4067)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3624)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3674)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3643)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3750)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3651)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3807)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3624)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3674)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3643)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3651)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3624)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5836)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5816)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5787)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5925)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5889)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5948)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
    at android.view.Choreographer.doCallbacks(Choreographer.java:593)
    at android.view.Choreographer.doFrame(Choreographer.java:560)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5314)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by TonicArtos** [comment]
This project is no longer supported and has been replaced by [SuperSLiM](https://github.com/TonicArtos/SuperSLiM). While SuperSLiM is still in heavy development, I already consider it much better and more stable than StickyGridHeaders. SuperSLiM also sees regular versioned releases.

**Comment by hendrawd** [comment]
But from the last version of SuperSLiM that i used(0.4.13), we can't detect end of scroll. Can you confirm that it works now?
