### ISSUE TITLE
Error log on small devices like samsung trend

### ISSUE THREAD

**Issue by kalkub** [TonicArtos/StickyGridHeaders#116]
Hi, i have problem on small devices like samsung trend and another, but on Samsung galaxy s4 is it ok.

Here is log:

java.lang.NullPointerException
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:559)
    at android.view.View.measure(View.java:16482)
    at com.tonicartos.widget.stickygridheaders.StickyGridHeadersGridView.measureHeader(StickyGridHeadersGridView.java:544)
    at com.tonicartos.widget.stickygridheaders.StickyGridHeadersGridView.scrollChanged(StickyGridHeadersGridView.java:602)
    at com.tonicartos.widget.stickygridheaders.StickyGridHeadersGridView.onScroll(StickyGridHeadersGridView.java:229)
    at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1754)
    at android.widget.GridView.layoutChildren(GridView.java:1306)
    at android.widget.AbsListView.onLayout(AbsListView.java:2426)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
    at android.view.View.layout(View.java:14905)
    at android.view.ViewGroup.layout(ViewGroup.java:4601)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2213)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2027)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
    at android.view.Choreographer.doCallbacks(Choreographer.java:591)
    at android.view.Choreographer.doFrame(Choreographer.java:561)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:176)
    at android.app.ActivityThread.main(ActivityThread.java:5317)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by TonicArtos** [comment]
Is the header larger than the screen?
